services:
  cowrie:
    restart: unless-stopped
    build:
      context: ./honeypot/cowrie
      dockerfile: ../cowrie-dockerfile.custom
      args:
          SETUPTOOLS_SCM_PRETEND_VERSION_FOR_COWRIE: "2.6.0"
    ports:
      - "2222:2222"
      - "2223:2223"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true

volumes:
  cowrie-etc:
  cowrie-var:
