# correlation/matching.py
# Stage 3 — Build entity-centric indices, then match alerts via
# explicitly author-defined CORRELATION_PAIRS / CORRELATION_CHAINS.
#
# Design recap (agreed in this project's Phase 5 design session):
#   - Two separate indices: {username: [alerts]} and {source_ip: [alerts]}.
#     Some rules (e.g. rule_006, CloudTrail) only ever have source_ip,
#     never username/auid — a username-only index can't reach them.
#   - Built FRESH each run, from the alerts loader.py already loaded —
#     matches the stateless, full-rescan design (no persisted state).
#   - An auid-bearing alert (e.g. rule_008, once fixed) must be resolved
#     to a username via identity.py BEFORE it can enter the username
#     index — the index itself only ever stores by username, never auid.
#   - Direct alert-to-alert comparison only (see GraphWeaver discussion
#     in decisions-and-learnings.md) — no separate entity-graph model.

from datetime import timedelta
from typing import Optional, NamedTuple
from schemas import Alert, Severity
from correlation.identity import resolve_uid_to_username
from correlation.correlation_rules import CORRELATION_RULES


def build_username_index(alerts: list[Alert], uid_cache: dict[int, str]) -> dict[str, list[Alert]]:
    """
    Build {username: [alerts]} from the full loaded alert list.

    For each alert:
      - if alert.username is already set, use it directly (preferred —
        it's the rule's own direct claim, not a resolved/derived value)
      - elif alert.auid is set, resolve it via resolve_uid_to_username()
        (silent skip if that returns None — see identity.py's own
        silent-skip design for auid=None / failed lookups)
      - else, this alert has no username-shaped identity at all —
        does NOT enter this index (it may still enter the source_ip
        index, if it has one)

    A single alert can never realistically have BOTH a real username
    AND a resolvable auid at once, given how the rules are structured
    today — each rule's detect() takes exactly one event type
    (AuthLogEvent, AuditdEvent, or CloudTrailEvent), so an Alert only
    ever carries the identity shape native to its own source. The
    username-first ordering below is just a safe default in case that
    ever changes, not a guard against a currently-real scenario.
    """
    index: dict[str, list[Alert]] = {}

    for alert in alerts:
        username = alert.username

        if username is None and alert.auid is not None:
            username = resolve_uid_to_username(alert.auid, uid_cache)

        if username is None:
            continue  # no username-shaped identity — sits out of this index

        index.setdefault(username, []).append(alert)

    return index


def build_source_ip_index(alerts: list[Alert]) -> dict[str, list[Alert]]:
    """
    Build {source_ip: [alerts]} from the full loaded alert list.

    Simpler than the username index — source_ip is always a direct
    field on Alert already (no resolution step needed, no Stage 2
    dependency). An alert with source_ip=None simply doesn't enter
    this index.
    """
    index: dict[str, list[Alert]] = {}

    for alert in alerts:
        if alert.source_ip is None:
            continue
        index.setdefault(alert.source_ip, []).append(alert)

    return index


def build_indices(
    alerts: list[Alert],
) -> tuple[dict[str, list[Alert]], dict[str, list[Alert]], dict[int, str]]:
    """
    Convenience wrapper — builds both indices in one call, sharing one
    uid_cache across the whole run (per Stage 2's per-run caching design).

    Returns (username_index, source_ip_index, uid_cache) — the cache
    is returned too so callers outside index-building (like the
    orchestration loop below) can keep reusing it, rather than each
    silently re-resolving auids that were already resolved once here.
    """
    uid_cache: dict[int, str] = {}
    username_index = build_username_index(alerts, uid_cache)
    source_ip_index = build_source_ip_index(alerts)
    return username_index, source_ip_index, uid_cache


# ── Correlation window — a Stage 3 matching parameter, distinct from
# WHICH rules relate (that lives in correlation_rules.py) ─────────────
CORRELATION_WINDOW_HOURS = 2


def get_identity(alert: Alert, uid_cache: dict[int, str]) -> Optional[str]:
    """
    Resolve a single alert's identity to a username — same logic as
    build_username_index() uses per-alert, but callable standalone for
    a single anchor alert rather than the whole list.
    """
    if alert.username is not None:
        return alert.username
    if alert.auid is not None:
        return resolve_uid_to_username(alert.auid, uid_cache)
    return None


def event_start(alert: Alert):
    """
    When the underlying activity BEGAN. Alert.timestamp is when the
    alert was GENERATED by the engine (see the Alert schema docstring),
    which can lag the real event by a whole engine cycle or more, so
    correlation must not use it. Falls back to timestamp only for
    alerts that carry no event time at all.
    """
    return alert.first_seen or alert.timestamp


def event_end(alert: Alert):
    """
    When the underlying activity ENDED. For aggregated alerts this is
    last_seen (e.g. rule_007: the moment the login succeeded). For
    single-event alerts (last_seen is None) start and end are the same.
    """
    return alert.last_seen or alert.first_seen or alert.timestamp


def find_nearest_preceding_match(
    anchor: Alert,
    candidate_rule_id: str,
    username_index: dict[str, list[Alert]],
    uid_cache: dict[int, str],
    window_hours: float = CORRELATION_WINDOW_HOURS,
) -> Optional[Alert]:
    """
    Given an anchor alert, find the nearest-preceding alert of
    `candidate_rule_id` for the SAME resolved identity, within
    `window_hours` before the anchor's own timestamp.

    Returns None if:
      - the anchor's own identity can't be resolved at all (nothing
        to search by)
      - no candidate alerts exist for that identity
      - candidates exist for that identity, but none are BOTH the
        right rule_id AND within the time window before the anchor
    """
    identity = get_identity(anchor, uid_cache)
    if identity is None:
        return None  # no identity to search by — can't match at all

    same_person_alerts = username_index.get(identity, [])

    window = timedelta(hours=window_hours)
    anchor_started = event_start(anchor)

    # Compare EVENT time, not alert-generation time: a candidate
    # qualifies if its activity ENDED before the anchor's activity
    # STARTED, within the window.
    valid_candidates = [
        alert for alert in same_person_alerts
        if alert.rule_id == candidate_rule_id
        and event_end(alert) < anchor_started
        and (anchor_started - event_end(alert)) <= window
    ]

    if not valid_candidates:
        return None

    return max(valid_candidates, key=event_end)


class GroupMatch(NamedTuple):
    """
    One matched group for an anchor — which candidate alert it found
    (the winner within that group's fallback tiers), the severity that
    tier earns, and which specific rule_id actually matched.
    """
    matched: Alert
    severity: Severity
    candidate_rule_id: str


# Severity is a str Enum — naive max()/sort on the values compares
# ALPHABETICALLY ("CRITICAL" < "HIGH" alphabetically, backwards from
# actual severity meaning), not by real severity rank. Explicit
# ranking required whenever comparing across Severity values.
SEVERITY_ORDER = {
    Severity.INFO: 0,
    Severity.LOW: 1,
    Severity.MEDIUM: 2,
    Severity.HIGH: 3,
    Severity.CRITICAL: 4,
}


def highest_severity(severities: list[Severity]) -> Severity:
    """
    Given multiple severities (e.g. from several independently-matched
    groups on one anchor), return the single highest one — by real
    severity rank, NOT Python's default string comparison.
    """
    return max(severities, key=lambda s: SEVERITY_ORDER[s])


class AnchorMatches(NamedTuple):
    """
    ALL matched groups for one anchor alert, combined. Stage 4 builds
    ONE CorrelatedIncident from this — not one per matched group —
    since matched groups together tell one combined story about the
    same anchor (e.g. both "breach preceded this" AND "persistence
    account also created").
    """
    anchor: Alert
    group_matches: list[GroupMatch]


def run_correlation(
    alerts: list[Alert],
) -> list[AnchorMatches]:
    """
    The real orchestration loop, group-aware.

    For every alert whose rule_id has entries in CORRELATION_RULES:
      - for EACH group configured for that anchor rule (groups are
        independent — all are checked, regardless of other groups'
        results):
          - try each (candidate_rule_id, severity) tier within that
            group, in order — first successful match wins THAT group,
            stop trying weaker tiers within it
      - if at least one group produced a match, emit ONE AnchorMatches
        combining every group that matched
      - if ZERO groups matched, emit nothing for this anchor at all
        (per the earlier design decision — only alerts that ARE part
        of a chain get surfaced in the correlation display window)
    """
    username_index, _source_ip_index, uid_cache = build_indices(alerts)

    results: list[AnchorMatches] = []

    for alert in alerts:
        groups = CORRELATION_RULES.get(alert.rule_id)
        if not groups:
            continue  # this alert's rule isn't configured as an anchor at all

        matched_groups: list[GroupMatch] = []

        for group in groups:
            for candidate_rule_id, severity in group:
                match = find_nearest_preceding_match(
                    anchor=alert,
                    candidate_rule_id=candidate_rule_id,
                    username_index=username_index,
                    uid_cache=uid_cache,
                )
                if match is not None:
                    matched_groups.append(GroupMatch(
                        matched=match,
                        severity=severity,
                        candidate_rule_id=candidate_rule_id,
                    ))
                    break  # first successful tier wins WITHIN this group

        if matched_groups:
            results.append(AnchorMatches(anchor=alert, group_matches=matched_groups))

    return results


def _make_synthetic_alert(
    rule_id: str,
    timestamp,
    auid: Optional[int] = None,
    username: Optional[str] = None,
    first_seen=None,
    last_seen=None,
) -> Alert:
    """Build a minimal, valid Alert for testing matching logic in
    isolation, without needing real alerts.json data. `timestamp` is
    the alert-GENERATION time; first_seen/last_seen are the real event
    times (left None to exercise the fallback to timestamp).
    """
    from schemas import ATTCKTechnique, Severity, LogSource
    return Alert(
        rule_id=rule_id,
        technique=ATTCKTechnique.T1053_003,   # placeholder, not checked by matching
        severity=Severity.HIGH,
        timestamp=timestamp,
        first_seen=first_seen,
        last_seen=last_seen,
        auid=auid,
        username=username,
        dedup_key=f"synthetic:{rule_id}:{timestamp.isoformat()}",
        log_source=LogSource.AUDITD,
        description="synthetic test alert",
    )


def _run_event_time_test() -> None:
    """
    Proves matching uses EVENT time (first_seen/last_seen), not
    alert-generation time (timestamp). Both alerts below are generated
    in the same engine run (nearly identical `timestamp`, candidate
    generated AFTER the anchor), so a generation-time comparison would
    reject the true match. Real event times say the breach ended at
    2:10 PM and the cron edit began at 2:30 PM.
    """
    from datetime import datetime, timezone

    print("\n" + "=" * 60)
    print("SYNTHETIC EVENT-TIME TEST (timestamp vs first_seen/last_seen)")
    print("=" * 60)

    def at(h, m):
        return datetime(2026, 1, 1, h, m, tzinfo=timezone.utc)

    run_time = at(15, 0)  # engine generated both alerts in this one run

    anchor = _make_synthetic_alert(
        "rule_008_cron_persistence",
        timestamp=run_time,
        auid=1000,
        first_seen=at(14, 30),
    )
    true_breach = _make_synthetic_alert(
        "rule_007_brute_force_success",
        timestamp=at(15, 0).replace(second=1),  # generated AFTER the anchor
        username="ubuntu",
        first_seen=at(14, 0),   # first failed attempt
        last_seen=at(14, 10),   # successful login
    )
    stale_breach = _make_synthetic_alert(
        "rule_007_brute_force_success",
        timestamp=at(15, 0),    # generated just now, but...
        username="ubuntu",
        first_seen=at(10, 0),
        last_seen=at(10, 5),    # ...the event was 4h+ before the anchor
    )

    username_index, _, uid_cache = build_indices([anchor, true_breach, stale_breach])
    result = find_nearest_preceding_match(
        anchor, "rule_007_brute_force_success", username_index, uid_cache
    )

    assert result is not None, (
        "No match — comparison is still using generation time, so the "
        "candidate (generated after the anchor) was wrongly rejected"
    )
    assert result.last_seen == at(14, 10), (
        f"Matched the wrong breach (last_seen={result.last_seen}); the 10:05 "
        f"one is 4h+ before the anchor and must be excluded by the window"
    )
    print("  PASS — matched the breach whose EVENT ended 20 min before the "
          "anchor, even though it was generated after it; excluded the "
          "breach generated 'recently' but which happened 4h earlier")


def _run_synthetic_matching_test() -> None:
    """
    Proves find_nearest_preceding_match() works correctly using
    hand-built alerts with KNOWN, controlled timestamps and identities
    — independent of whether real production alerts.json has caught
    up with the auid= fix yet (Path B, per project decision).

    Three cases:
      1. A valid match WITHIN the window — should succeed.
      2. A candidate OUTSIDE the window — should return None.
      3. No candidate at all for that identity — should return None.
    """
    from datetime import datetime, timezone

    print("=" * 60)
    print("SYNTHETIC MATCHING TEST (controlled, not real alerts.json)")
    print("=" * 60)

    anchor_time = datetime(2026, 1, 1, 15, 0, tzinfo=timezone.utc)  # 3:00 PM

    # Case 1: valid match, 40 minutes before anchor, same identity (auid=1000 -> "ubuntu")
    candidate_good = _make_synthetic_alert(
        rule_id="rule_007_brute_force_success",
        timestamp=anchor_time.replace(hour=14, minute=20),  # 2:20 PM
        username="ubuntu",
    )

    # Case 2: same identity, same rule_id, but OUTSIDE the 2-hour window
    candidate_too_old = _make_synthetic_alert(
        rule_id="rule_007_brute_force_success",
        timestamp=anchor_time.replace(hour=12, minute=0),  # 12:00 PM — 3 hours before
        username="ubuntu",
    )

    anchor = _make_synthetic_alert(
        rule_id="rule_008_cron_persistence",
        timestamp=anchor_time,
        auid=1000,  # resolves to "ubuntu" via real /etc/passwd
    )

    username_index, _, uid_cache = build_indices([anchor, candidate_good, candidate_too_old])

    result = find_nearest_preceding_match(
        anchor, "rule_007_brute_force_success", username_index, uid_cache
    )
    print(f"\nCase 1+2 combined (good match exists, along with a too-old one):")
    print(f"  Matched: {result.dedup_key if result else None}")
    assert result is not None, "Expected a match, got None"
    assert result.dedup_key == candidate_good.dedup_key, (
        f"Matched the WRONG alert — got {result.dedup_key}, "
        f"expected the 2:20 PM one, not the 12:00 PM one"
    )
    print("  PASS — matched the nearer (2:20 PM) candidate, correctly "
          "ignored the too-old (12:00 PM) one")

    # Case 3: no candidate at all for a different identity
    lonely_anchor = _make_synthetic_alert(
        rule_id="rule_008_cron_persistence",
        timestamp=anchor_time,
        auid=999999,  # doesn't resolve to anyone real
    )
    result = find_nearest_preceding_match(
        lonely_anchor, "rule_007_brute_force_success", username_index, uid_cache
    )
    print(f"\nCase 3 (anchor's identity can't even be resolved):")
    print(f"  Matched: {result}")
    assert result is None, "Expected None for an unresolvable identity"
    print("  PASS — correctly returned None")

    print("\nAll synthetic matching tests passed.")


def _run_synthetic_orchestration_test() -> None:
    """
    Proves run_correlation() correctly handles groups:
      1. Within a group, first-match-wins (rule_007 beats rule_001).
      2. ACROSS groups, matches are COMBINED into one AnchorMatches,
         not treated as competing — if Group 2 (persistence account)
         is enabled, a rule_008 anchor matching BOTH the breach group
         AND the persistence-account group should produce ONE
         AnchorMatches with TWO group_matches, not two separate results.

    NOTE: this test temporarily adds a Group 2 into CORRELATION_RULES
    at runtime, since the real config currently has it commented out
    — proves the group-combining logic works even though it's not
    live in production config yet.
    """
    from datetime import datetime, timezone

    print("\n" + "=" * 60)
    print("SYNTHETIC ORCHESTRATION TEST (run_correlation, groups)")
    print("=" * 60)

    # Temporarily enable a second, independent group for this test only.
    # Patch this module's OWN global namespace directly (not a re-import
    # of correlation.matching — when this file is run as __main__ via
    # `python3 -m correlation.matching`, a self-import creates a SEPARATE
    # module object with its own independent globals, so patching that
    # copy would silently never affect the run_correlation() actually
    # executing here. globals() always refers to whichever module
    # instance is really running this code.)
    global CORRELATION_RULES
    original_rules = CORRELATION_RULES
    CORRELATION_RULES = {
        "rule_008_cron_persistence": [
            [
                ("rule_007_brute_force_success", Severity.CRITICAL),
                ("rule_001_ssh_brute_force", Severity.MEDIUM),
            ],
            [
                ("rule_003_new_user_created", Severity.HIGH),
            ],
        ],
    }

    try:
        anchor_time = datetime(2026, 1, 1, 15, 0, tzinfo=timezone.utc)

        anchor = _make_synthetic_alert(
            rule_id="rule_008_cron_persistence",
            timestamp=anchor_time,
            auid=1000,  # -> "ubuntu"
        )
        rule_007_candidate = _make_synthetic_alert(
            rule_id="rule_007_brute_force_success",
            timestamp=anchor_time.replace(hour=14, minute=20),
            username="ubuntu",
        )
        rule_001_candidate = _make_synthetic_alert(
            rule_id="rule_001_ssh_brute_force",
            timestamp=anchor_time.replace(hour=14, minute=10),
            username="ubuntu",
        )
        rule_003_candidate = _make_synthetic_alert(
            rule_id="rule_003_new_user_created",
            timestamp=anchor_time.replace(hour=14, minute=45),
            username="ubuntu",
        )

        results = run_correlation([
            anchor, rule_007_candidate, rule_001_candidate, rule_003_candidate,
        ])

        print(f"\nAnchorMatches produced: {len(results)}")
        assert len(results) == 1, f"Expected exactly 1 AnchorMatches, got {len(results)}"

        anchor_matches = results[0]
        print(f"  anchor={anchor_matches.anchor.dedup_key}")
        print(f"  group_matches: {len(anchor_matches.group_matches)}")
        for gm in anchor_matches.group_matches:
            print(f"    matched={gm.matched.dedup_key} severity={gm.severity} "
                  f"via={gm.candidate_rule_id}")

        assert len(anchor_matches.group_matches) == 2, (
            f"Expected 2 group_matches (breach group + persistence group), "
            f"got {len(anchor_matches.group_matches)}"
        )

        matched_rule_ids = {gm.candidate_rule_id for gm in anchor_matches.group_matches}
        assert matched_rule_ids == {"rule_007_brute_force_success", "rule_003_new_user_created"}, (
            f"Expected matches via rule_007 (not rule_001 — first-tier-wins "
            f"within the breach group) AND rule_003, got {matched_rule_ids}"
        )

        print("\nPASS — Group 1 matched rule_007 (not the weaker rule_001, "
              "correct first-tier-wins), Group 2 independently matched "
              "rule_003, BOTH combined into one AnchorMatches.")
    finally:
        # restore real config so nothing else in this run is affected
        CORRELATION_RULES = original_rules


if __name__ == "__main__":
    from correlation.loader import load_alerts

    print("Loading real alerts...")
    alerts = load_alerts()
    print(f"Loaded {len(alerts)} alerts.\n")

    username_index, source_ip_index, _uid_cache = build_indices(alerts)

    print(f"Username index: {len(username_index)} distinct usernames")
    for username, entries in sorted(username_index.items()):
        print(f"  {username}: {len(entries)} alert(s)")

    print(f"\nSource IP index: {len(source_ip_index)} distinct IPs")
    for ip, entries in sorted(source_ip_index.items()):
        print(f"  {ip}: {len(entries)} alert(s)")

    indexed_ids = set()
    for entries in username_index.values():
        indexed_ids.update(id(a) for a in entries)
    for entries in source_ip_index.values():
        indexed_ids.update(id(a) for a in entries)

    unindexed = [a for a in alerts if id(a) not in indexed_ids]
    print(f"\n{len(unindexed)} / {len(alerts)} alerts landed in NEITHER "
          f"index (no username, no resolvable auid, no source_ip).")
    if unindexed:
        from collections import Counter
        print("By rule_id:", dict(Counter(a.rule_id for a in unindexed)))

    print()
    _run_synthetic_matching_test()
    _run_synthetic_orchestration_test()
    _run_event_time_test()